### PR TITLE
Fixes to make the Better Folders plugin not look like shit.

### PR DESCRIPTION
**Pull request by solonovamax**
Also, there's a fix for the Online Friends Count plugin, because it looked stupid too.

Also also, I just copied the main css file into it, so I could modify it directly lol

### CODE REVIEW

**Comment by yellowsink** [comment]
Looks good to me after testing

**Comment by solonovamax** [comment]
actually, I have another fix I want to push

**Comment by yellowsink** [comment]
oh ok sure before i merge lol

**Comment by solonovamax** [comment]
wait shit, I removed your commit because I force pushed lol

**Comment by yellowsink** [comment]
np i'll just remake it lmao

**Comment by yellowsink** [comment]
I just thought you should get credit too for your fixes

**Comment by solonovamax** [comment]
> np i'll just remake it lmao

I'm faster :+1:

**Comment by yellowsink** [comment]
oh no you redid it for me cool

**Comment by yellowsink** [comment]
lol ok sure i'll merge it yea?

**Comment by solonovamax** [comment]
ye, pretty sure it's fine

I'll make a new pr if I find any other issues

**Comment by yellowsink** [comment]
k

**Comment by yellowsink** [comment]
Thanks a lot! :)

**Pull request merged**
